In [1]:
import numpy as np

In [2]:
a = np.arange(15).reshape(3,5)

In [3]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape

(3, 5)

In [5]:
a.ndim

2

In [6]:
a.dtype.name

'int32'

In [7]:
a.itemsize

4

In [50]:
b = np.array([6,7,8])

In [9]:
b

array([6, 7, 8])

In [10]:
type(b)

numpy.ndarray

In [19]:
b= np.array([(6,7,8), (4,3,2)], dtype = complex)

In [20]:
b

array([[6.+0.j, 7.+0.j, 8.+0.j],
       [4.+0.j, 3.+0.j, 2.+0.j]])

In [21]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [23]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)

In [26]:
c = a-b
c

array([20, 29, 38, 47])

In [27]:
b**2

array([0, 1, 4, 9])

In [28]:
a*b  # elementwise product 

array([  0,  30,  80, 150])

In [29]:
a@b # matrix product 

260

In [34]:
rg = np.random.default_rng(1) 
a = rg.random((2,3))
a.sum()

3.290252281866131

In [35]:
x = np.arange(10)**3
x

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [36]:
x[2:4]

array([ 8, 27], dtype=int32)

In [40]:
x[:5:2] = 100
x

array([100,   1, 100,  27, 100, 125, 216, 343, 512, 729], dtype=int32)

In [43]:
x[::-1]

array([729, 512, 343, 216, 125, 100,  27, 100,   1, 100], dtype=int32)

In [46]:
def f(x, y):
    return 10 * x + y
b = np.fromfunction(f, (5, 4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [47]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [48]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43
